### ISSUE TITLE
Unable to update and keep user Session valid ( try await supabase.auth.session )

### ISSUE THREAD

**Issue by joshuabourke** [supabase-community/supabase-swift#159] opened 2023-11-14 03:35 UTC
# Bug report
### 
try await supabase.auth.session

## Describe the bug

For some reason even though I was calling for a new session or checking if the session needed to be updated. Nothing would happen, this could be on my end but I was checking the session on the start-up of the app. After a while, my users kept getting 400 and 401 errors from supabase.

I am now using 'try await supabase.auth.session.user' to see if there is any difference. I am using it pretty similar to the way it is used here in this video

https://www.youtube.com/watch?v=XBSiXROUoZk&ab_channel=MikaelaCaron

timestamp 25:33 minutes.

## Expected behavior

I am wanting my users to be authed all the time and not be required to log back in, if possible. I know after some time they may be required to, but I am just trying to get as much time out of a single session.

## To reproduce.

trying to insert a row or upload an image with out a valid access token.

**Comment by joshuabourke** [comment] 2023-11-14 22:56
Hey @grdsdev I am using 0.3

<img width="1508" alt="Screenshot 2023-11-15 at 8 55 58 am" src="https://github.com/supabase-community/supabase-swift/assets/24494726/3a5270dd-7f5f-48cf-b2ec-d859aa020259">

**Comment by grdsdev** [comment] 2023-12-05 21:46
Could you update to `1.0` and let me know if the issue persists? You may have to make a few changes as it contains breaking changes.

I'm here if you have trouble doing that, just let me know.

**Comment by joshuabourke** [comment] 2023-12-05 23:02
Ok, I shall try changing to 1.0 and see what happens then. I will keep you posted with how to convert to 1.0 goes

**Comment by joshuabourke** [comment] 2023-12-06 00:21
@grdsdev Do you recommend running 1.0.0 over 0.3.0? This may be a silly question but thought I'd still ask.

**Comment by grdsdev** [comment] 2023-12-06 00:38
Yes @joshuabourke , `1.0.0` was released 2 weeks ago, and is recommended that you update ASAP, there was a lot of bug fixes on it, and I hope this issue you're having also got fixed.

**Comment by MadeByDouglas** [comment] 2023-12-14 08:59
Just wanted to chime in here, not sure its the best place but maybe we can help each other in the process.

When I was using 0.3 it would persist the session across app launches. I'm not sure how it did this, it just seemed to work if that is what one wanted (which I did).
Now with 1.1, it will not persist, and after each app reload user must sign in again.

Is this expected behavior or not? What is the recommended way to persist session data? Should I be saving something myself in like UserDefaults or is there an option to check on the supabase client during init?

Also I use the new `authStateChanges` (which returns a session now vs the old `authEvents`) to have my app respond to app session events like sign in and out, should I be doing something with the new `.initialSession` option?

**Comment by grdsdev** [comment] 2023-12-14 19:35
Hey @MadeByDouglas 

Using the latest version should also persist the session across app launches by default.

The `initialSession` event emits when the client is first initialized, and it represents the persisted session, if any.

Checkout the https://github.com/supabase-community/supabase-swift/blob/main/Examples/UserManagement/AppView.swift#L23 example on how to do it.

**Comment by MadeByDouglas** [comment] 2023-12-15 02:19
@grdsdev awesome! yep that example was what I needed to connect the dots. And I realized before in the code I was grabbing the `client.auth.session` manually which is why it worked in 0.3 but I removed that code when I refactored with 1.1, anyways using the `initialsession` as the example shows works like a charm and its less network calls since those updates come in anyway at the right times.

**Comment by grdsdev** [comment] 2023-12-15 11:54
Since seems to be fixed on the latest releases, I'm going to close the issue.

Feel free to reopen it if the issue persists.

**Closed by grdsdev** 2023-12-15 11:54 UTC
Labels: bug, gotrue
